package it.gianluca;

public class File {

	String a = "<!DOCTYPE html>\r\n"
			+ "<html>\r\n"
			+ "<head>\r\n"
			+ "<style>\r\n"
			+ "html{\r\n"
			+ "height:100vh;\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".papi{\r\n"
			+ "display:flex;\r\n"
			+ "flex-direction:row;\r\n"
			+ "}\r\n"
			+ ".block {\r\n"
			+ "  margin:2px;\r\n"
			+ "  display: block;\r\n"
			+ "  width: 33.3%;\r\n"
			+ "  border: none;\r\n"
			+ "  background-color: #04AA6D;\r\n"
			+ "  color: white;\r\n"
			+ "  padding: 14px 28px;\r\n"
			+ "  font-size: 16px;\r\n"
			+ "  cursor: pointer;\r\n"
			+ "  text-align: center;\r\n"
			+ "  padding-top:7%;\r\n"
			+ "  padding-bottom:7%;\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".block:hover {\r\n"
			+ "  background-color: #ddd;\r\n"
			+ "  color: black;\r\n"
			+ "}\r\n"
			+ ".all-browsers {\r\n"
			+ "  margin: 0;\r\n"
			+ "  padding: 5px;\r\n"
			+ "  background-color: lightgray;\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".all-browsers > h1, .browser {\r\n"
			+ "  margin: 10px;\r\n"
			+ "  padding: 5px;\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".browser {\r\n"
			+ "  background: white;\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ ".browser > h2, p {\r\n"
			+ "  margin: 4px;\r\n"
			+ "  font-size: 90%;\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "footer {\r\n"
			+ "  text-align: center;\r\n"
			+ "  padding: 40px;\r\n"
			+ "  background-color: DarkSalmon;\r\n"
			+ "  color: white;\r\n"
			+ "  width-top: auto;\r\n"
			+ "}\r\n"
			+ "ul {\r\n"
			+ "  list-style-type: none;\r\n"
			+ "  margin: 0;\r\n"
			+ "  padding: 0;\r\n"
			+ "  overflow: hidden;\r\n"
			+ "  background-color: #333;\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "li {\r\n"
			+ "  float: left;\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "li a {\r\n"
			+ "  display: block;\r\n"
			+ "  color: white;\r\n"
			+ "  text-align: center;\r\n"
			+ "  padding: 14px 16px;\r\n"
			+ "  text-decoration: none;\r\n"
			+ "}\r\n"
			+ "\r\n"
			+ "li a:hover {\r\n"
			+ "  background-color: #111;\r\n"
			+ "}\r\n"
			+ "</style>\r\n"
			+ "</head>\r\n"
			+ "<body>\r\n"
			+ "\r\n"
			+ "<ul>\r\n"
			+ "  <li><a class=\"active\" href=\"#home\">Home</a></li>\r\n"
			+ "  <li><a href=\"#news\">News</a></li>\r\n"
			+ "  <li><a href=\"#contact\">Contact</a></li>\r\n"
			+ "  <li><a href=\"#about\">About</a></li>\r\n"
			+ "</ul>\r\n"
			+ "\r\n"
			+ "<div class=\"papi\"><button class=\"block\">DDT</button>\r\n"
			+ "<button class=\"block\">FatturaAccompagnatoria</button>\r\n"
			+ "<button class=\"block\">Fattura</button></div>\r\n"
			+ "<div class=\"papi\"><button class=\"block\">FatturaAnalogica</button>\r\n"
			+ "<button class=\"block\">FatturaInversa</button>\r\n"
			+ "<button class=\"block\">NotaDiCredito</button></div>\r\n"
			+ "<div class=\"papi\"><button class=\"block\">NotaDiDebito</button>\r\n"
			+ "<button class=\"block\">Ordine</button>\r\n"
			+ "<button class=\"block\">Preventivo</button></div>\r\n"
			+ "\r\n"
			+ "<footer>\r\n"
			+ "  <p style='font-size:20px'>Author: TielloCasa<br>\r\n"
			+ "  <a href=\"https://github.com/TielloCasa/tomcat\">il mio Github</a></p>\r\n"
			+ "</footer>\r\n"
			+ "\r\n"
			+ "</body>\r\n"
			+ "</html>\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "";
	
	
	
	
	public String stampa() {
		return a;
	}
	
	
	
}
